version: '3.8'

volumes:
  postgres_data:
  redis_data:

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    ports:
      - "${PROJECT_PORT}:${PROJECT_PORT}"
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    stop_signal: SIGINT
    stop_grace_period: ${STOP_GRACE_PERIOD}

  golangci:
    image: golangci/golangci-lint:v1.56.2
    working_dir: /app
    volumes:
      - ./:/app

  postgres:
    image: postgres:13-alpine
    environment:
      PGPORT: 5432
      POSTGRES_DB: short_links
      POSTGRES_PASSWORD: pa55word
      POSTGRES_USER: go
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis_data:/var/lib/redis
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
