version: '3.8'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    ports:
      - "${PROJECT_PORT}:${PROJECT_PORT}"
    volumes:
      - ./:/app
    env_file:
      - .env
