name: Link shorter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: short_links
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: go
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      env:
        POSTGRES_HOST: postgres
        TEST_DEFAULT_DSN: postgres://go:secret@localhost:5432/short_links?sslmode=disable
        TEST_DSN: postgres://go:secret@localhost:5432/short_links?sslmode=disable
